---
title: "Presentation"
output:
  pdf_document:
    extra_dependencies:
      babel : ["english", "russian"]
    keep_tex: true
    latex_engine: xelatex
---

```{r include=FALSE}
library(jpeg)
library(knitr)
library(kableExtra)
library(tidyverse)
```

```{r tidy = TRUE}
file1 <- "resources/Adams_The_Tetons_and_the_Snake_River.jpg"
file2 <- "resources/Herbert_von_Karajan.jpg"
file3 <- "resources/Austria.jpg"
file4 <- "resources/Colosseum.jpg"
```

```{r tidy = TRUE}
isRGB <- TRUE
fle <- file4
image <- readJPEG(fle)
image.size <- file.info(fle)$size
if (length(dim(image)) == 2) {
  isRGB <- FALSE
}
if (isRGB) {
  rimage <- image[,,1]
  gimage <- image[,,2]
  bimage <- image[,,3]
  rorig_mean <- rowMeans(rimage)
  gorig_mean <- rowMeans(gimage)
  borig_mean <- rowMeans(bimage)
  rimage <- rimage - rorig_mean
  gimage <- gimage - gorig_mean
  bimage <- bimage - borig_mean
  
} else {
  orig_mean <- rowMeans(image)
  image <- image - orig_mean
}
```

```{r tidy = TRUE}
if (isRGB) {
  pcar <- prcomp(rimage, center=FALSE)
  pcag <- prcomp(gimage, center=FALSE)
  pcab <- prcomp(bimage, center=FALSE)
  pcaimage <- list(pcar, pcag, pcab)
} else {
  pcaimage <- prcomp(image, center=F)
}
```

```{r tidy = TRUE}
pcnum <- c(1, 50, 100, 200, 400, 800, 1200)
compr_rate <- c()
pic_name <- str_remove(fle, "resources/")
for(i in pcnum){
    if (isRGB) {
      pca.img <- sapply(pcaimage, function(j){
        compressed.img <- j$x[, 1:i] %*% t(j$rotation[, 1:i])
      }, simplify='array')
      pca.img[,,1] <- pca.img[,,1] + rorig_mean
      pca.img[,,2] <- pca.img[,,2] + gorig_mean
      pca.img[,,3] <- pca.img[,,3] + borig_mean
    } else {
      pca.img <- pcaimage$x[, 1:i]  %*% t(pcaimage$rotation[, 1:i]) + orig_mean
    }
    pca.img.name <- paste("with_",i, "comps_",pic_name,sep = "")
    writeJPEG(pca.img, paste("reconstructions/", pca.img.name, sep = ""))
    pca.img.size <- file.info(paste("reconstructions/", pca.img.name, sep = ""))$size
    compr_rate <- c(compr_rate, image.size / pca.img.size)
}
content <- data.frame(pcnum, round(compr_rate, digits = 2))
table_name <- paste("tables/", "CR_for_", str_remove(pic_name, "jpg"), "pdf", sep = "")
col_names <- c("$k$", "$CR$")
knitr::kable(content, format = "latex", col.names = col_names, align = c("c","c"), escape = F) %>%
column_spec(1, border_left = T) %>% column_spec(2, border_right = T) %>%   save_kable(table_name)
```
```{r tidy = TRUE}
components <- 1:20
pic_name <- str_remove(fle, "resources/")
if (isRGB) {
  columns_fillers <- c("red2", "green3", "steelblue")
  col_comp <- c("Red", "Green", "Blue")
  for (i in 1:3) {
    var_exp <- ((pcaimage[[i]]$sdev)^2/sum((pcaimage[[i]]$sdev)^2) * 100)[components]
    df <- data.frame(PC = paste0("PC", components), var_exp)
    df$PC <- factor(df$PC, levels = df$PC)
    ggplot(df, aes(x = PC, y = var_exp)) + geom_col(fill=columns_fillers[i]) + labs(y = "% of variance explained", x = "")
    hist_name <- paste("hists/", col_comp[i], "hist_for_",str_remove(pic_name, "jpg"), "pdf", sep = "")
    ggsave(hist_name, device = "pdf", width = 9)
  }
  
} else {
  var_exp <- ((pcaimage$sdev)^2/sum((pcaimage$sdev)^2) * 100)[components]
  df <- data.frame(PC = paste0("PC", components), var_exp)
  df$PC <- factor(df$PC, levels = df$PC)
  df %>% ggplot(aes(x=PC, y=var_exp)) + geom_col() + labs(y = "% of variance explained", x = "")
  hist_name <- paste("hists/", "hist_for_", str_remove(pic_name, "jpg"), "pdf", sep = "")
  ggsave(hist_name, device = "pdf", width = 9)
}
```


